In [3]:
import numpy as np
A = np.array([
[0.582745, 0.48, 0.10	, 0.  	, 0.  	], 
 [0.48	, 1.044129, 0.46	, 0.10	, 0.  	],
 [0.10	, 0.46	, 1.10431 , 0.44	, 0.10	],
 [0.  	, 0.10	, 0.44	, 0.963889, 0.42	],
 [0.  	, 0.  	, 0.10	, 0.42	, 0.522565]], dtype=float)
b = np.array([1.162745, 2.084129, 2.20431 , 1.923889, 1.042565], dtype=float)
x0 = np.zeros_like(b)

def is_diagonal(A):
    for i in range(len(A)):
        dval = np.abs(A[i][i])
        sum = 0
        for j in range(len(A[0])):
            if(j == i):
                sum = sum + 0
            else:
                sum = sum + np.abs(A[i][j])
        if(dval < sum):
            return False
    return True

print("A:")
print(A)
print(is_diagonal(A))  

A:
[[0.582745 0.48     0.1      0.       0.      ]
 [0.48     1.044129 0.46     0.1      0.      ]
 [0.1      0.46     1.10431  0.44     0.1     ]
 [0.       0.1      0.44     0.963889 0.42    ]
 [0.       0.       0.1      0.42     0.522565]]
True


In [4]:
C = np.array([[1, 2, 3, 0, 0], [2, 1, 2, 3, 0], [3, 2, 1, 2, 3], [0, 3, 2, 1, 2], [0, 0, 3, 2, 1]])
print("A:")
print(C)
print(is_diagonal(C)) 

A:
[[1 2 3 0 0]
 [2 1 2 3 0]
 [3 2 1 2 3]
 [0 3 2 1 2]
 [0 0 3 2 1]]
False
