Linear Algebra

In [2]:
import numpy as np

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [5]:
v_add = v1 + v2
v_sub = v1 - v2

print(v_add)
print(v_sub)

scalar = 5
v_scaled = v1 * scalar
print(v_scaled)

[5 7 9]
[-3 -3 -3]
[ 5 10 15]


In [6]:
dot_product = np.dot(v1,v2)
print(dot_product)

32


In [8]:
#Norm is the magnituude of the vector
magnitude_v1 = np.linalg.norm(v1)
print(magnitude_v1)

3.7416573867739413


In [10]:
A = np.array([[1,2,3],[4,5,6]])
print(A)

B = np.array([[7,8,9],[10,11,12],[13,14,15]])
print(B)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [16]:
C = np.array([[1,2,3],[4,5,6]])

matrix_add = A + C
print(matrix_add)

[[ 2  4  6]
 [ 8 10 12]]


In [19]:
matrix_mul = np.dot(A,B)
print(matrix_mul)

[[ 66  72  78]
 [156 171 186]]


In [20]:
transpose_a = A.T
print(transpose_a)

[[1 4]
 [2 5]
 [3 6]]


Let's discuss systems of linear equations: take Ax = b, where A is the coefficient matrix, x is the unknown vector, and b is the constant vector

given:
2x + 3y = 5
4x - y = 3

In [22]:
A = np.array([[2,3],[4,-1]])
b = np.array([5,3])
print(A,b)
x = np.linalg.solve(A,b)
print(x)

[[ 2  3]
 [ 4 -1]] [5 3]
[1. 1.]


Eigenvalue - given Av - lambda * v, lambda is a scalara and v is a nonzero vector
lambda is your eigenvalue, and v is the eigenvactor

eigenvectors are directions that don't change when a matrix acts on them(directions of maximum variance in data)
eigenvalues control the magnitude of the eigenvectors(how important each direction is)


In [25]:
A = np.array([[2,1],[1,2]])
eigenvalues, eigenvectors = np.linalg.eig(A)

In [26]:
print(eigenvalues,eigenvectors)

[3. 1.] [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [29]:
A = np.array([[4,7],[2,6]])
A_inv = np.linalg.inv(A)
identity = np.dot(A,A_inv)
print(identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


gaussian elim

In [32]:
def gaussian_elimination(A, b):
    n = len(b)
 # Forward elimination
    for i in range(n):
 # Pivoting
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]
    # Backward substitution
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    return x

In [33]:
A = [[3, 2, -4], [2, 3, 3], [5, -3, 1]]
b = [3, 15, 14]
solution = gaussian_elimination(A, b)
print(f"Solution: {solution}")

Solution: [2.9999999999999996, 0.9999999999999996, 2.0]


In [35]:
ans = np.linalg.solve(A,b) #Does the EXACT same thing
print(ans)

[3. 1. 2.]


In [37]:
def lu_decomposition(A):
    n = len(A)
    L = np.eye(n) # Initialize L as an identity matrix
    U = np.array(A, dtype=float) # Copy of A to avoid
    # modifying the original matrix
    for i in range(n):
         # Eliminate elements below the pivot (U[i, i])
        for j in range(i+1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
                factor = U[j, i] / U[i, i] # Multiplier for row
                 # operation
                L[j, i] = factor # Store multiplier in L
                 # Update the rows of U
                for k in range(i, n):
                    U[j, k] -= factor * U[i, k]
    return L, U

In [38]:
A = np.array([[2, 3, 1],
 [4, 7, -1],
 [-2, 1, 2]])
L, U = lu_decomposition(A)
print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Lower Triangular Matrix L:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Upper Triangular Matrix U:
 [[ 2.  3.  1.]
 [ 4.  7. -1.]
 [-2.  1.  2.]]
